Burger.Web/Models/DTOs/LoginDTO.cs
using System.ComponentModel.DataAnnotations;

namespace Burger.Web.Models.DTOs
{
    public class LoginDTO
    {
        [Required]
        [MinLength(4, ErrorMessage = "Email Alani en az 5 karakter olmaildir")]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string RememberMe { get; set; }
    }
}

Burger.Web/Models/DTOs/RegisterDTO.cs
using System.ComponentModel.DataAnnotations;

namespace Burger.Web.Models.DTOs
{
    public class RegisterDTO
    {
        [Required]
        public string Ad { get; set; }
        [Required]
        public string Soyad { get; set; }
        [Required]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Compare("Password")]
        public string RePassword { get; set; }
        public string IAgree { get; set; }

    }
}

Burger.Web/Models/ErrorViewModel.cs
namespace Burger.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Burger.Web/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Burger.Web.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        [Area("Admin")]
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Burger.Web/Controllers/HomeController.cs
using Burger.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Burger.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Burger.Web/Controllers/KategoriController.cs
using Burger.BL.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace Burger.Web.Controllers
{
    public class KategoriController : Controller
    {
        private readonly IKategoriManager manager;

        public KategoriController(IKategoriManager manager)
        {
            this.manager = manager;
        }


        public IActionResult Index()
        {
            var sonuc = manager.GetAll();

            return View();
        }
    }
}

Burger.Web/Controllers/UserController.cs
using Burger.BL.Abstract;
using Burger.Entities;
using Burger.Web.Models.DTOs;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Burger.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserManager manager;

        public UserController(IUserManager manager)
        {
            this.manager = manager;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginDTO loginDTO)
        {
            if (ModelState.IsValid)
            {
                var user = manager.GetAll(p => p.Email == loginDTO.Email && p.Password == loginDTO.Password).FirstOrDefault();
                if (user != null)
                {
                    var claims = new List<Claim>
                    {
                      new Claim(ClaimTypes.Name,user.Username),
                      new Claim(ClaimTypes.Email,user.Email),
                      new Claim(ClaimTypes.Role,user.Role),

                    };
                    var userIdentity = new ClaimsIdentity(claims, "login");
                    ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);
                    HttpContext.SignInAsync(principal);

                    return RedirectToAction("index", "Home", new { Area = "Admin" });
                }

            }
            return View(loginDTO);
        }



        [HttpGet]
        public IActionResult Register()
        {
            RegisterDTO dTO = new();
            return View(dTO);
        }
        [HttpPost]
        public IActionResult Register(RegisterDTO dTO)
        {
            if (ModelState.IsValid)
            {
                Kullanicilar yeniKullanici = new();
                yeniKullanici.Ad = dTO.Ad;
                yeniKullanici.Soyad = dTO.Soyad;
                yeniKullanici.Email = dTO.Email;
                yeniKullanici.Password = dTO.Password;
                yeniKullanici.Role = "User";
                yeniKullanici.Username = dTO.UserName;
                manager.Add(yeniKullanici);
                return RedirectToAction("Login", "User");
            }
            return View(dTO);

        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }


}

Burger.Web/Areas/Admin/Views/Home/Index.cshtml
<h4> Admin/Home</h4>

Burger.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Burger.Web/Views/Kategori/Index.cshtml
@model IEnumerable<Kategori>
<a class="btn btn-primary" asp-action="Create">Yeni Kategori</a>
<table class="table table-hover">
    <thead>
        <tr>
            <td>@Html.DisplayNameFor(p=>p.Id)</td>
            <td>@Html.DisplayNameFor(p=>p.KategoriAdi)</td>
            <td>@Html.DisplayNameFor(p=>p.Aciklama)</td>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.KategoriAdi</td>
                <td>@item.Aciklama</td>
                <td>
                    <a class="btn btn-primary" asp-action="Create">Guncelle</a>
                    <a class="btn btn-primary" asp-action="Create">Sil</a>
                
                </td>


            </tr>
        }


    </tbody>
</table>

Burger.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Burger.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
   <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Burger.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Burger.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @{
                            if (Context.User.Identity.IsAuthenticated) // Burasi cookie ile oturum acilmismi onu kontrol eder
                            { 
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Kategori" asp-action="Index">Kategoriler</a>
                              </li>

                             <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Update">Hosşgeldiniz @Context.User.Identity.Name</a>
                              </li>

                              <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                              </li>
                            
                            }else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                                </li>
                            }
                        }
                        

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Burger.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/dist/js/adminlte.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Burger.Web/Views/User/Login.cshtml
@model LoginDTO

<link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">

<div class="login-box">
  <div class="login-logo">
    <a asp-action="Index"><b>Admin</b>LTE</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Sign in to start your session</p>

      <form asp-action="Login" method="post">
        <div class="input-group mb-3">
          <input type="email" class="form-control" placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <div class="social-auth-links text-center mb-3">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
        </a>
      </div>
      <!-- /.social-auth-links -->

      <p class="mb-1">
        <a href="forgot-password.html">I forgot my password</a>
      </p>
      <p class="mb-0">
        <a  asp-action="Register" class="text-center">Yeni Üye</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>

Burger.Web/Views/User/Register.cshtml
@model RegisterDTO

<div class="register-box">
  <div class="register-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
  </div>

  <div class="card">
    <div class="card-body register-card-body">
      <p class="login-box-msg">Register a new membership</p>

      <form asp-action="Register" method="post">

        <div class="input-group mb-3">
          <input asp-for="Ad" class="form-control" placeholder="Adiniz">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>

         <div class="input-group mb-3">
          <input asp-for="Soyad" class="form-control" placeholder="Soyadiniz">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>

        <div class="input-group mb-3">
          <input asp-for="UserName" class="form-control" placeholder="Full name">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input asp-for="Email" class="form-control" placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input asp-for="Password" class="form-control" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input asp-for="RePassword" class="form-control" placeholder="Retype password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="agreeTerms" asp-for="IAgree" value="agree">
              <label for="agreeTerms">
               I agree to the <a href="#">terms</a>
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Register</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <div class="social-auth-links text-center">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i>
          Sign up using Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i>
          Sign up using Google+
        </a>
      </div>

      <a href="login.html" class="text-center">I already have a membership</a>
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>